name: Build and deploy Node.js app to Azure Web App - projectricotta(dev)

     # For override below, see https://github.com/adrienverge/yamllint/issues/430
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'projectricotta-dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'projectricotta-dev'
          slot-name: 'projectricotta-dev'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_f2f5546ef3b74ad88fb8ac0c8872bc6e }}
          package: .
